---
abstract: 'A tool for managing dynamic website menus.'
author:
  - 'Andrew Rodland <andrew@hbslabs.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-MenuGrinder
requires:
  Moose: 0.34
  XML::Simple: 0
version: 0.04
